name: Publish 

on:
  push:
    branches: 
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - run: npm publish --access public
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}