name: Publish 

on:
  push:
    paths: 
      - package.json
    branches: 
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
